Repository Azure/az-hop, pull requests merged in 2021-10, with the labels that each got.

#550 typo in rbh_sku name
  tf/variables_local.tf
Labels: fix

#553 fix password generation
  playbooks/lustre.yml
Labels: fix

#554 Update lustre
  config.tpl.yml
  playbooks/lustre.yml
  tf/lustre.tf
Labels: breaking-change

#556 Update root certificates
  .github/workflows/integration.yml
  playbooks/ood.yml
Labels: fix

#561 Update rover and check config yaml syntax
  build.sh
  install.sh
  packer/build_image.sh
  toolset/scripts/install.sh
Labels: kind/feature

#563 Trailing space
  .yamllint
  build.sh
  install.sh
  packer/.yamllint
  packer/build_image.sh
Labels: fix

#562 create user accounts in cyclecloud
  playbooks/add_users.yml
  playbooks/create_user.yml
  playbooks/roles/cyclecloud/files/user_role_record.txt
  playbooks/templates/user_record.txt.j2
Labels: kind/feature

#559 add checkpointing in the install script
  .gitignore
  docs/deploy/install.md
  install.sh
Labels: kind/feature
