Repository Azure/az-hop, pull requests merged in 2021-08, with the labels that each got.

#444 Allow deploying with an SPN account
  docs/deploy/azure_prereqs.md
  docs/deploy/deploy.md
  tf/ccportal.tf
  tf/keyvault.tf
  tf/lustre.tf
  tf/main.tf
  tf/network.tf
Labels: kind/feature

#454 Dedicated VM for hosting Grafana
  config.tpl.yml
  playbooks/chrony.yml
  playbooks/grafana.yml
  playbooks/linux.yml
  playbooks/roles/grafana/dashboards/azhop_infra_servers.json
  playbooks/roles/grafana/dashboards/cpu-nodes.json
  playbooks/roles/grafana/dashboards/lustre-and-hsm.json
  playbooks/roles/grafana/dashboards/scheduler-stats.json
  playbooks/roles/ood-apps-grafana/files/grafana/app.py
  playbooks/telegraf.yml
  tf/grafana.tf
  tf/outputs.tf
  tf/templates/inventory.tmpl
Labels: breaking-change

#456 use configured vnet address_space in chorny.conf
  playbooks/chrony.yml
Labels: kind/feature

#455 make cycle/jetpack RPMs optional
  .github/workflows/configs/integration.yml
  .github/workflows/configs/production.yml
  .github/workflows/configs/shared.yml
  .github/workflows/configs/validation.yml
  config.tpl.yml
  docs/deploy/define_environment.md
  playbooks/ccportal.yml
Labels: fix

#457 move to CycleCloud 8.2
  .github/workflows/configs/integration.yml
  .github/workflows/configs/production.yml
  .github/workflows/configs/shared.yml
  .github/workflows/configs/validation.yml
  config.tpl.yml
  docs/deploy/define_environment.md
  tf/ccportal.tf
Labels: kind/feature

#459 use new format dashboard
  playbooks/roles/grafana/dashboards/azhop_infra_servers.json
Labels: fix

#461 enable AN on the OnDemand VM
  config.tpl.yml
  docs/deploy/define_environment.md
  tf/ondemand.tf
Labels: breaking-change

#460 admin users are domain admins
  playbooks/create_user.yml
Labels: kind/feature

#464 update template with pre-defined images
  config.tpl.yml
  packer/azhop-centos78-v2-rdma.json
  packer/centos77-v1-rdma-gpgpu.json
  packer/centos77-v2-rdma-gpgpu.json
Labels: kind/feature

#466 upgrade to PBS scalelib 2.0.5
  playbooks/roles/pbsserver/defaults/all.yml
  playbooks/roles/pbsserver/files/resources.json
  playbooks/roles/pbsserver/tasks/main.yml
Labels: kind/feature

#467 chmod 777 /lustre
  playbooks/ood.yml
Labels: fix

#472 Fix quoting in the lfs_hsm_remove.sh script
  playbooks/lustre.yml
Labels: fix
