Repository Azure/az-hop, pull requests merged in 2022-02, with the labels that each got.

#731 use queues in config.yml for running tests jobs
  install.sh
  playbooks/roles/tests/files/job.sh
  playbooks/roles/tests/files/job_gpu.sh
  playbooks/roles/tests/files/test.sh
  playbooks/roles/tests/tasks/main.yml
  playbooks/roles/tests/vars/main.yml
  playbooks/tests.yml
Labels: kind/CICD

#734 provide ondemand fqdn for SSL certificate
  config.tpl.yml
  docs/deploy/define_environment.md
  tf/outputs.tf
Labels: kind/feature

#737 provide SSL certificate
  .gitignore
  config.tpl.yml
  docs/deploy/define_environment.md
  docs/deploy/how_to.md
  playbooks/ood.yml
Labels: kind/feature

#741 create az-hop-admins group
  playbooks/ad.yml
  playbooks/create_user.yml
  playbooks/roles/grafana/templates/ldap.toml.j2
Labels: kind/feature

#736 Added multi-cloud support for Lustre
  build.sh
  playbooks/lustre.yml
  tf/outputs.tf
  tf/templates/global_variables.tmpl
  tf/variables.tf
  tf/variables_local.tf
Labels: kind/feature

#743 Feature/user_mapping
  config.tpl.yml
  docs/deploy/define_environment.md
  playbooks/files/custom_mapping.sh
  playbooks/ood-overrides-auth-oidc.yml
  playbooks/ood.yml
Labels: kind/feature

#745 Added support to peer to multiple vnets
  config.tpl.yml
  docs/deploy/define_environment.md
  tf/network_peering.tf
  tf/variables_local.tf
Labels: kind/feature

#747 Multiple vnet peering support
  .github/workflows/configs/integration.yml
  tf/variables_local.tf
Labels: kind/feature

#752 Force playbook execution when a playbook is specified
  docs/deploy/configure_toolchain.md
  docs/deploy/how_to.md
  docs/deploy/install.md
  install.sh
Labels: kind/feature

#753 Ui_testing
  tests/file_explorer.spec.ts
  tests/home.spec.ts
  tests/interactive_apps.spec.ts
  tests/jobs.spec.ts
  tests/playwright.config.ts
Labels: kind/CICD

#765 allow user names with a .
  .github/workflows/configs/integration.yml
  create_passwords.sh
  playbooks/create_user.yml
  tf/templates/get_secret.tmpl
Labels: fix

#766 custom ssh port for jumpbox
  .github/workflows/configs/integration.yml
  .gitignore
  config.tpl.yml
  docs/deploy/build_images.md
  docs/deploy/define_environment.md
  packer/azhop-centos79-v2-rdma-gpgpu.json
  packer/azhop-ubuntu18.04.json
  packer/build_image.sh
  packer/centos-7.8-desktop-3d.json
  packer/templates/options.json.tmpl
  packer/templates/options_nopip.json.tmpl
  playbooks/ad.yml
  playbooks/add_users.yml
  playbooks/remove_users.yml
  playbooks/winviz.yml
  tf/cloud-init/empty.yml
  tf/jumpbox.tf
  tf/outputs.tf
  tf/templates/connect.tmpl
  tf/templates/global_variables.tmpl
  tf/templates/inventory.tmpl
  tf/templates/jumpbox_ci.tmpl
  tf/variables_local.tf
Labels: kind/feature, breaking-change

#764 update sudo description
  config.tpl.yml
Labels: kind/feature

#771 Fix/770
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/5-default.sh.j2
Labels: fix
