Repository Azure/az-hop, pull requests merged in 2022-11, with the labels that each got.

#1181 rename node before domain join
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2
Labels: kind/feature

#1158 improved nhc error handling
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/azhop-node-offline.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/azhop_nhc.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/nhc_common.conf.j2
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/8-configure-nhc.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/99-healthcheck.sh
  playbooks/roles/slurmserver/templates/epilog.sh.j2
  playbooks/roles/slurmserver/templates/slurm.conf.j2
Labels: kind/feature, area/slurm

#1185 Order image by published date
  playbooks/cccluster.yml
Labels: fix

#1187 Don't failed Health Check if telegraf is not running. Stop azsecd.
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/nhc_common.conf.j2
Labels: kind/feature

#1194 Default configuration file use the CentOS 7.9 azhop marketplace images
  config.tpl.yml
  docs/deploy/define_environment.md
Labels: kind/feature

#1184 Add deployment and cyclecloud telemetry values
  config.tpl.yml
  deploy/deploy.sh
  deploy/resources/bicep-templates/outputs.bicep.j2
  deploy/resources/bicep-templates/telemetry.bicep.j2
  deploy/resources/generate_bicep.py
  docs/deploy/index.md
  docs/deploy/telemetry.md
  playbooks/roles/cyclecloud/tasks/main.yml
  tf/main.tf
  tf/variables_local.tf
Labels: kind/feature

#1199 no pub ip self-signed cert fails
  playbooks/ood.yml
Labels: fix

#1202 Remove hard coded NFS mount option for the home directory
  .github/workflows/configs/integration.yml
  config.tpl.yml
  docs/deploy/define_environment.md
  tf/outputs.tf
  tf/templates/global_variables.tmpl
Labels: fix

#1203 install jetpack with yum repo
  playbooks/roles/slurmserver/tasks/main.yml
Labels: fix

#1205 update OpenOnDemand version to 2.0.29
  playbooks/ood.yml
Labels: kind/feature

#1211 set Ansible get_url timeout to 180s instead of 10s
  playbooks/guacamole.yml
  playbooks/ood.yml
  playbooks/roles/slurmserver/tasks/accounting.yml
  playbooks/roles/slurmserver/tasks/main.yml
Labels: fix

#1215 don't check for NFS type in mount healthchecks
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/nhc_common.conf.j2
Labels: fix

#1209 Adding Jupyter application
  deploy/resources/azhop-config-templates/config.yml.j2
  playbooks/ood-overrides-slurm.yml
Labels: kind/feature

#1212 install and configure xarchiver in the remote desktop CentOS 7.9 Image
  packer/scripts/centos/interactive-desktop-3d.sh
Labels: fix

#1213 Update to CycleCloud 8.3
  config.tpl.yml
  docs/deploy/define_environment.md
  playbooks/ccportal.yml
  playbooks/roles/slurmserver/defaults/main.yml
  playbooks/roles/slurmserver/tasks/main.yml
  playbooks/scheduler.yml
Labels: kind/feature

#1220 changed pyxis temp dir to /mnt/resource
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/5-default.sh.j2
  playbooks/roles/cyclecloud_cluster/projects/enroot/cluster-init/scripts/2-install_enroot.sh.j2
  playbooks/roles/slurmserver/tasks/pyxis.yml
  playbooks/roles/slurmserver/templates/prolog.sh.j2
Labels: area/container, area/slurm
