Repository Azure/az-hop, pull requests merged in 2022-12, with the labels that each got.

#1233 use latest version of telegraf agent
  packer/scripts/almalinux/telegraf.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/almalinux/init_telegraf.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/centos/init_telegraf.sh
Labels: kind/feature

#1228 Switch from MySQL single server to MariaDB managed database
  deploy/resources/bicep-templates/mariadb.bicep.j2
  deploy/resources/generate_bicep.py
  playbooks/guacamole.yml
  playbooks/ood.yml
  playbooks/roles/cyclecloud_cluster/vars/main.yml
  playbooks/roles/guac_spooler/defaults/main.yml
  playbooks/roles/guac_spooler/tasks/main.yml
  playbooks/roles/slurmserver/tasks/main.yml
  tf/mariadb.tf
  tf/mysql.tf_
  tf/outputs.tf
Labels: kind/feature, breaking-change

#1237 Add version of azhop in footer
  playbooks/ood.yml
Labels: kind/feature

#1241 do not mount Cycle data disk if already mounted
  playbooks/roles/cyclecloud/tasks/main.yml
Labels: fix

#1246 Add Ansys Workbench integration
  .github/workflows/configs/integration.yml
  config.tpl.yml
  deploy/resources/azhop-config-templates/config.yml.j2
  docs/deploy/define_environment.md
  playbooks/roles/ood-applications/defaults/main.yml
  playbooks/roles/ood-applications/files/bc_ansys_workbench/form.yml.erb
  playbooks/roles/ood-applications/files/bc_ansys_workbench/icon.png
  playbooks/roles/ood-applications/files/bc_ansys_workbench/manifest.yml
  playbooks/roles/ood-applications/files/bc_ansys_workbench/readme.md
  playbooks/roles/ood-applications/files/bc_ansys_workbench/submit.yml.erb
  playbooks/roles/ood-applications/files/bc_ansys_workbench/template/before.sh.erb
  playbooks/roles/ood-applications/files/bc_ansys_workbench/template/script.sh.erb
  playbooks/roles/ood-applications/tasks/main.yml
Labels: kind/feature

#1250 fix alma 8.5 version to 8.5.20211210
  packer/azhop-almalinux85-v2-rdma-gpgpu.json
Labels: fix

#1253 no need to be root to retrieve the azhop version with git
  playbooks/ood.yml
Labels: fix

#1252 PBS : Enable enroot and the Jupyter Notebook application
  playbooks/roles/cyclecloud_cluster/projects/enroot/cluster-init/scripts/2-install_enroot.sh.j2
  playbooks/roles/cyclecloud_cluster/projects/enroot/cluster-init/scripts/3-pmix.sh.j2
  playbooks/roles/cyclecloud_cluster/tasks/main.yml
  playbooks/roles/cyclecloud_cluster/templates/azhop-OpenPBS.txt.j2
  playbooks/roles/ood-applications/defaults/main.yml
  playbooks/roles/ood-applications/files/bc_jupyter/manifest.yml
  playbooks/roles/ood-applications/files/bc_jupyter/submit.yml.erb
  playbooks/roles/ood-applications/files/bc_jupyter/template/before.sh.erb
  playbooks/roles/ood-applications/files/bc_jupyter/template/get_container.sh
  playbooks/roles/ood-applications/files/bc_jupyter/template/script.sh.erb
  playbooks/roles/ood-applications/files/bc_jupyter/template/start_container.sh
  playbooks/roles/ood-applications/files/bc_jupyter/template/start_jupyter.sh
Labels: kind/feature

#1258 suppress xfce message on startup
  playbooks/roles/ood-applications/files/bc_ansys_workbench/template/script.sh.erb
Labels: kind/bug, area/ood

#1257 added VMD GUI application
  config.tpl.yml
  playbooks/roles/ood-applications/defaults/main.yml
  playbooks/roles/ood-applications/files/bc_vmd/form.yml.erb
  playbooks/roles/ood-applications/files/bc_vmd/icon.png
  playbooks/roles/ood-applications/files/bc_vmd/manifest.yml
  playbooks/roles/ood-applications/files/bc_vmd/readme.md
  playbooks/roles/ood-applications/files/bc_vmd/submit.yml.erb
  playbooks/roles/ood-applications/files/bc_vmd/template/before.sh.erb
  playbooks/roles/ood-applications/files/bc_vmd/template/script.sh.erb
Labels: kind/feature, area/ood

#1255 Update rpc service dependencies
  config.tpl.yml
  deploy/resources/bicep-templates/anf.bicep.j2
  docs/deploy/index.md
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/1-mountnfs.sh.j2
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
  playbooks/roles/domain_join/tasks/main.yml
  tf/outputs.tf
Labels: fix

#1263 Access to a new or an existing Azure Database for MariaDB Server behind a private endpoint
  config.tpl.yml
  deploy/resources/azhop-config-templates/global_variables.j2
  docs/deploy/index.md
  playbooks/guac_spooler.yml
  playbooks/guacamole.yml
  playbooks/roles/guac_spooler/tasks/main.yml
  playbooks/roles/guac_spooler/vars/main.yml
  playbooks/roles/slurmserver/tasks/accounting.yml
  playbooks/roles/slurmserver/templates/slurmdbd.conf.j2
  tf/main.tf
  tf/mariadb.tf
  tf/network.tf
  tf/network/main.tf
  tf/outputs.tf
  tf/templates/global_variables.tmpl
  tf/variables_local.tf
Labels: kind/feature

#1268 add support for the nct4-v3-series for Linux Remote Desktop
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/5-default.sh.j2
Labels: kind/feature

#1264 Use SLURM packages provided by CycleCloud
  config.tpl.yml
  docs/deploy/index.md
  packer/scripts/almalinux/slurm.sh
  packer/scripts/centos/slurm.sh
  packer/scripts/ubuntu/slurm.sh
  playbooks/cccluster.yml
  playbooks/ood.yml
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
  playbooks/roles/cyclecloud_cluster/vars/main.yml
  playbooks/roles/slurmclient/tasks/main.yml
  playbooks/roles/slurmserver/defaults/main.yml
  playbooks/roles/slurmserver/files/cgroup.conf
  playbooks/roles/slurmserver/tasks/accounting.yml
  playbooks/roles/slurmserver/tasks/main.yml
  playbooks/roles/slurmserver/templates/slurm.conf.j2
  playbooks/scheduler.yml
Labels: kind/feature, area/cyclecloud, area/slurm

#1270 revisit and document new IP ranges
  .github/workflows/configs/integration.yml
  config.tpl.yml
  deploy/build.tpl.yml
  docs/deploy/index.md
  tf/network.tf
Labels: kind/feature

#1272 Fix issue with Jumpbox when deploying ANF in Dual Mode
  tf/active_directory/outputs.tf
  tf/main.tf
Labels: fix
