Repository Azure/az-hop, pull requests merged in 2022-10, with the labels that each got.

#1107 advanced healthchecks using nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/almalinux/init_nhc.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/centos/init_nhc.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/healthchecks.json
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/healthchecks.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/azhop_nhc.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/nhc_common.conf.j2
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/nhc_hb120rs_v3.conf
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/nhc_nd96asr_v4.conf
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/nhc_sample.conf
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/az-hop.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/csc_nvidia_smi.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/gpu_app_clocks.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/gpu_clock_throttling.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/gpu_ecc.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/gpu_persistence.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/gpu_xid.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/ubuntu/init_nhc.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/0-healthcheck.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/8-configure-nhc.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/99-healthcheck.sh
  playbooks/roles/cyclecloud_cluster/tasks/main.yml
  playbooks/roles/slurmserver/tasks/main.yml
  playbooks/roles/slurmserver/tasks/pyxis.yml
  playbooks/roles/slurmserver/templates/epilog.sh.j2
  playbooks/roles/slurmserver/templates/slurm.conf.j2
Labels: kind/feature, area/monitoring

#1108 removed job_submit plugin from compute node images
  packer/scripts/almalinux/slurm.sh
  packer/scripts/centos/slurm.sh
  packer/scripts/ubuntu/slurm.sh
Labels: fix, area/slurm

#1109 Linux Remote Desktop : Allow 1, 1/2, 1/4, 1/8 node buckets
  .github/workflows/configs/integration.yml
  config.tpl.yml
  docs/deploy/define_environment.md
  playbooks/ood-overrides-common.yml
  playbooks/ood-overrides-openpbs.yml
  playbooks/ood-overrides-slurm.yml
Labels: kind/feature

#1110 set repo version for the ondemand remote desktop app
  playbooks/ood-overrides-guacamole.yml
Labels: kind/feature

#1113 build and publish images to Azure marketplace
  .github/workflows/marketplace_image.yml
  marketplace/auth.sh
  marketplace/build_offer_file.sh
  marketplace/copyosdisk.sh
  marketplace/icon-generator/azhop_compute.png
  marketplace/icon-generator/azhop_desktop.png
  marketplace/icon-generator/icongen.sh
  marketplace/icon-generator/iconupload.sh
  marketplace/readme.md
  packer/azhop-compute-centos-7_9.json
  packer/azhop-desktop-centos-7_9.json
  packer/build_image.sh
Labels: kind/feature

#1114 added SLURM Grafana dashboard
  playbooks/roles/grafana/dashboards/slurm-stats.json
  playbooks/telegraf.yml
Labels: kind/feature

#1115 nhc documentation
  docs/operate/healthcheck.md
  docs/operate/index.md
Labels: documentation, area/documentation

#1118 NFS mount options as parameters
  playbooks/linux.yml
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/almalinux/mountnfs.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/centos/mountnfs.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/ubuntu/mountnfs.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/1-mountnfs.sh.j2
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
  playbooks/roles/domain_join/tasks/main.yml
  playbooks/roles/domain_join/vars/main.yml
  tf/templates/global_variables.tmpl
Labels: kind/feature

#1121 create the scripts directory for prolog and epilog
  playbooks/roles/slurmserver/tasks/main.yml
Labels: fix

#1124 failed node core lookup task in case of failure
  playbooks/nodearray_lookup.yml
Labels: fix

#1125 adminuser with sudo access
  config.tpl.yml
  docs/deploy/define_environment.md
Labels: fix

#1126 define the mount options in config file
  .github/workflows/configs/integration.yml
  config.tpl.yml
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
Labels: kind/feature

#1138 build marketplace images with OpenPBS and SLURM clients
  packer/azhop-compute-centos-7_9.json
  packer/azhop-desktop-centos-7_9.json
Labels: kind/feature

#1142 fixed the url in nhc doc
  docs/operate/healthcheck.md
Labels: kind/bug

#1143 grant reader subscription role to ccportal
  tf/ccportal.tf
Labels: kind/feature

#1140 renamed vnet peerings, added vnet_allow_gateway setting
  config.tpl.yml
  tf/network_peering.tf
Labels: kind/feature

#1145 update yq version to v4.25.3
  toolset/scripts/install.sh
Labels: kind/feature

#1149 add custom scripts placeholders for cluster init scripts and image customization
  docs/deploy/build_images.md
  docs/operate/how_to.md
  packer/azhop-almalinux85-v2-rdma-gpgpu.json
  packer/azhop-centos79-desktop3d-ci.json
  packer/azhop-centos79-desktop3d.json
  packer/azhop-centos79-v2-rdma-ci.json
  packer/azhop-centos79-v2-rdma-gpgpu.json
  packer/azhop-compute-centos-7_9.json
  packer/azhop-desktop-centos-7_9.json
  packer/azhop-ubuntu18.04.json
  packer/scripts/almalinux/zz-compute-custom.sh
  packer/scripts/almalinux/zz-desktop-custom.sh
  packer/scripts/centos/zz-compute-custom.sh
  packer/scripts/centos/zz-desktop-custom.sh
  packer/scripts/ubuntu/zz-compute-custom.sh
  packer/scripts/ubuntu/zz-desktop-custom.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/zz-custom.sh
Labels: kind/feature

#1153 New parameter to configure the max scaleset size per queue
  config.tpl.yml
  docs/deploy/define_environment.md
  playbooks/roles/cyclecloud_cluster/templates/azhop-OpenPBS.txt.j2
  playbooks/roles/cyclecloud_cluster/templates/azhop-remoteviz.txt.j2
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
Labels: kind/feature

#1155 added full path to the jetpack binary
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/azhop_nhc.sh
Labels: fix

#1156 New quickstart tutorial
  deploy/deploy.sh
  deploy/pre-reqs.sh
  docs/tutorials/Implementing_Azure_HPC_OnDemand_Platform.md
  docs/tutorials/Implementing_Azure_HPC_OnDemand_Platform_Lab_1.md
  docs/tutorials/index.md
  docs/tutorials/quickstart.md
  tutorials/quickstart/build.yml
Labels: kind/feature

#1168 Fix guacamole database error creation
  playbooks/guacamole.yml
Labels: fix

#1169 Fix error when re-applying ccportal playbook
  playbooks/roles/cyclecloud/tasks/main.yml
Labels: fix

#1170 Delete Winviz session request
  docs/operate/how_to.md
  playbooks/roles/guac_spooler/defaults/main.yml
  playbooks/roles/guac_spooler/tasks/main.yml
Labels: kind/feature

#1171 replace static RG in build_image.sh
  packer/build_image.sh
Labels: fix

#1174 fix CycleCloud mount disk marker file
  playbooks/roles/cyclecloud/tasks/main.yml
Labels: fix

#1176 updated code-server to 4.8.1 (slurm)
  playbooks/ood-overrides-slurm.yml
Labels: kind/feature, area/ood
