Repository Azure/az-hop, pull requests merged in 2022-06, with the labels that each got.

#874 Support for Windows Desktop
  .github/workflows/configs/integration.yml
  .github/workflows/main_callable.yml
  .gitignore
  config.tpl.yml
  docs/deploy/define_environment.md
  install.sh
  packer/azhop-win10.json
  packer/scripts/windows/install-choco.ps1
  packer/scripts/windows/optimize.ps1
  packer/scripts/windows/sysprep.ps1
  packer/scripts/windows/wait-for-agent.ps1
  playbooks/ad.yml
  playbooks/cccluster.yml
  playbooks/chrony.yml
  playbooks/create_user.yml
  playbooks/guac_spooler.yml
  playbooks/guacamole.yml
  playbooks/linux.yml
  playbooks/ood-overrides-common.yml
  playbooks/ood-overrides-guacamole.yml
  playbooks/ood.yml
  playbooks/roles/cyclecloud_cluster/defaults/all.yml
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/windows/4-configure-rdp.bat
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.bat.j2
  playbooks/roles/cyclecloud_cluster/tasks/main.yml
  playbooks/roles/cyclecloud_cluster/templates/azhop-remoteviz.txt.j2
  playbooks/roles/cyclecloud_cluster/vars/main.yml
  playbooks/roles/grafana/dashboards/azhop_infra_servers.json
  playbooks/roles/guac_spooler/defaults/main.yml
  playbooks/roles/guac_spooler/tasks/main.yml
  playbooks/roles/guac_spooler/vars/main.yml
  playbooks/telegraf.yml
  playbooks/winviz.yml
  tf/guacamole.tf
  tf/mysql.tf
  tf/network.tf
  tf/outputs.tf
  tf/templates/inventory.tmpl
  tf/variables_local.tf
  tf/winviz.tf
Labels: kind/feature

#892 enable windows desktop
  .github/workflows/configs/integration.yml
Labels: kind/CICD

#893 Windows Desktop
  run_ui_tests.sh
  tests/ood_interactive_apps.spec.ts
  tests/playwright.config.ts
Labels: kind/CICD

#898 don't run guac_spooler playbook if enable_remote_winviz is false
  install.sh
Labels: kind/bug

#902 fix for ib device visibility inside container
  playbooks/roles/cyclecloud_cluster/projects/enroot/cluster-init/scripts/2-install_enroot.sh.j2
Labels: fix

#907 force ssh bootstrap for intel mpi hydra bootstrap
  playbooks/files/ood_templates/openpbs/impi_pingpong/pingpong.sh
  playbooks/files/ood_templates/openpbs/impi_ring_pingpong/ring_pingpong.sh
Labels: fix

#909 added PMIx to the compute images
  packer/azhop-almalinux85-v2-rdma-gpgpu.json
  packer/azhop-centos79-v2-rdma-gpgpu.json
  packer/azhop-ubuntu18.04.json
  packer/scripts/almalinux/pmix.sh
  packer/scripts/centos/pmix.sh
  packer/scripts/ubuntu/pmix.sh
Labels: kind/feature

#911 New tutorials
  docs/tutorials/Implementing_Azure_HPC_OnDemand_Platform_Lab_1.md
  docs/tutorials/Implementing_Azure_HPC_OnDemand_Platform_Lab_2.md
  docs/tutorials/index.md
  docs/tutorials/osu_benchmarks.md
  scripts/arm/ubuntu_azurecli_vm_template.json
  scripts/arm/ubuntu_azurecli_vm_template.parameters.json
  tutorials/lab1/config.tpl.yml
Labels: kind/feature

#914 don't use special characters for mySql password
  tf/mysql.tf
Labels: fix

#915 use pip3 to install influxdb packages
  playbooks/roles/influxdb/tasks/main.yml
Labels: fix

#916 centos7 support for toolset
  ansible_prereqs.sh
  toolset/scripts/install_centos.sh
Labels: kind/feature

#918 use python3 to install grafana
  playbooks/grafana.yml
  playbooks/roles/influxdb/tasks/main.yml
Labels: fix

#919 latest lab documentation
  docs/tutorials/Implementing_Azure_HPC_OnDemand_Platform_Lab_1.md
  docs/tutorials/Implementing_Azure_HPC_OnDemand_Platform_Lab_2.md
Labels: kind/feature

#920 Use Azure Container Registry instead of Docker Hub for the toolset container
  .devcontainer/docker-compose.yml
  .github/workflows/container.yml
  toolset/build_container.sh
Labels: kind/feature

#925 Use VirtualGL official RPMs
  packer/scripts/centos/interactive-desktop-3d.sh
Labels: fix

#931 don't check certificate when downloading VirtualGL.repo
  packer/scripts/centos/interactive-desktop-3d.sh
Labels: fix
