Repository Azure/az-hop, pull requests merged in 2022-08, with the labels that each got.

#1017 delete terraform state file when the resource group name has changed in config.yml
  build.sh
Labels: fix

#1018 remove anfhome mount from slurm cluster template
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
Labels: fix

#1010 add --gpus=1 for GPU remote desktop jobs
  playbooks/ood-overrides-slurm.yml
Labels: fix

#1024 Build Windows Image without public IP
  packer/azhop-win10.json
  packer/build_image.sh
  tf/keyvault.tf
  tf/variables_local.tf
Labels: kind/feature

#1038 bump pyxis version to 0.12.0 (fix for sbatch)
  playbooks/roles/slurmserver/defaults/main.yml
Labels: area/container, fix, area/slurm

#1027 eval option missing from yq call
  build.sh
Labels: fix

#1043 upgrade cyclecloud-pbspro to release 2.0.15
  playbooks/roles/pbsserver/vars/main.yml
Labels: kind/feature

#1045 Create lustre container only when lustre is enabled
  tf/main.tf
  tf/outputs.tf
Labels: fix

#1047 manage multiple RG in state
  build.sh
Labels: fix

#1048 upgrade to terraform azurerm 3.19
  tf/main.tf
  tf/network/main.tf
Labels: kind/feature

#1052 add a PBS job submission hook
  playbooks/roles/pbsclient/tasks/main.yml
  playbooks/roles/pbsclient/vars/main.yml
  playbooks/roles/pbsserver/files/submit-hook.py
  playbooks/roles/pbsserver/tasks/main.yml
  playbooks/roles/pbsserver/vars/main.yml
Labels: fix

#1053 upgrade to ood 2.0.28
  playbooks/ood.yml
Labels: kind/feature

#1054 Configure PBS to use vcpu instead of pcpu
  playbooks/roles/pbsserver/tasks/main.yml
Labels: kind/feature

#1055 don't reject jobs with quotes in env variables, but replace the content with an error message
  playbooks/roles/pbsserver/files/submit-hook.py
Labels: fix

#1056 document image version pattern requirements
  config.tpl.yml
  docs/deploy/define_environment.md
Labels: documentation

#1059 Add SMB outbound rule for compute nodes
  tf/variables_local.tf
Labels: fix
