Repository Azure/az-hop, pull requests merged in 2022-07, with the labels that each got.

#935 Allow lustre to be installed on CentOS 7.9
  config.tpl.yml
  docs/deploy/define_environment.md
  playbooks/lustre.yml
  playbooks/ood.yml
  playbooks/roles/lustre/defaults/main.yml
  playbooks/roles/lustre/tasks/client.yml
  playbooks/roles/lustre/tasks/configure_client.yml
  playbooks/roles/lustre/tasks/configure_server.yml
  playbooks/roles/lustre/tasks/main.yml
  playbooks/roles/lustre/tasks/mds.yml
  playbooks/roles/lustre/tasks/oss.yml
  playbooks/roles/lustre/tasks/repos.yml
  playbooks/roles/lustre/tasks/robinhood.yml
  playbooks/roles/lustre/templates/lhsm-plugin-az.j2
  playbooks/roles/lustre/templates/lhsmd.service.j2
  playbooks/roles/lustre/templates/lustre.conf.j2
  tf/ccportal.tf
  tf/grafana.tf
  tf/guacamole.tf
  tf/jumpbox.tf
  tf/lustre.tf
  tf/ondemand.tf
  tf/scheduler.tf
  tf/variables_local.tf
Labels: kind/feature

#939 Users groups
  config.tpl.yml
  docs/deploy/add_users.md
  docs/deploy/define_environment.md
  playbooks/ad.yml
  playbooks/create_user.yml
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/5-default.sh.j2
  playbooks/templates/user_record.txt.j2
Labels: kind/feature

#938 Build SLURM client from source, instead of the one provided by CycleCloud.
  packer/azhop-almalinux85-v2-rdma-gpgpu.json
  packer/azhop-centos79-v2-rdma-gpgpu.json
  packer/azhop-ubuntu18.04.json
  packer/centos-7.8-desktop-3d.json
  packer/scripts/almalinux/enroot.sh
  packer/scripts/almalinux/openpbs.sh
  packer/scripts/almalinux/pmix.sh
  packer/scripts/almalinux/slurm.sh
  packer/scripts/centos/desktop-packages.sh
  packer/scripts/centos/enroot.sh
  packer/scripts/centos/openpbs.sh
  packer/scripts/centos/pmix.sh
  packer/scripts/centos/slurm.sh
  packer/scripts/ubuntu/openpbs.sh
  packer/scripts/ubuntu/pmix.sh
  packer/scripts/ubuntu/slurm.sh
  packer/templates/options.json.tmpl
  playbooks/ood.yml
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
  playbooks/roles/cyclecloud_cluster/vars/main.yml
  playbooks/roles/slurmserver/defaults/main.yml
  playbooks/roles/slurmserver/tasks/main.yml
  playbooks/scheduler.yml
  tf/outputs.tf
  tf/variables_local.tf
Labels: kind/feature, area/slurm

#952 Update azure_prereqs.md
  docs/deploy/azure_prereqs.md
Labels: documentation

#956 Update azure_prereqs.md
  docs/deploy/azure_prereqs.md
Labels: area/documentation

#955 config template: add documentation on ssh/anf
  config.tpl.yml
Labels: area/documentation

#958 Add environment variables for slurmd to allow using PMIx+IB from containers across nodes
  playbooks/roles/cyclecloud_cluster/projects/enroot/cluster-init/scripts/1-install_pyxis.sh.j2
  playbooks/roles/cyclecloud_cluster/projects/enroot/cluster-init/scripts/2-install_enroot.sh.j2
Labels: kind/feature, area/container, area/slurm

#962 update guac_spooler to version 0.1.18
  playbooks/guac_spooler.yml
Labels: fix

#963 exit on mount failure during node startup
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/almalinux/mountnfs.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/centos/mountnfs.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/ubuntu/mountnfs.sh
Labels: fix

#964 toolchain : exit on failure if any component is missing
  toolset/scripts/install.sh
Labels: fix

#966 use recommended read and write sizes when mounting ANF
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/almalinux/mountnfs.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/centos/mountnfs.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/ubuntu/mountnfs.sh
Labels: kind/feature

#960 Allow using custom images when building compute nodes and desktop3D centOS images
  config.tpl.yml
  docs/deploy/define_environment.md
  packer/azhop-centos79-desktop3d-ci.json
  packer/azhop-centos79-desktop3d.json
  packer/azhop-centos79-v2-rdma-ci.json
  packer/base-centos79-v2-rdma.json
  packer/build_image.sh
  packer/scripts/centos/hpc_image.sh
  packer/scripts/centos/interactive-desktop-3d.sh
  packer/scripts/centos/kernel-centos77.sh
  packer/scripts/centos/mellanox-ib.sh
  packer/scripts/centos/nvidia-gpgpu.sh
  packer/scripts/centos/rdma-udev-rules.sh
Labels: kind/feature

#969 Windows Desktop : install NFS client
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.bat.j2
Labels: kind/feature

#970 format and mount NVME disk when present
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/1-nvme.sh
Labels: kind/feature

#983 upgrade guac_spooler version to 0.1.19 to fix component version mismatch
  playbooks/guac_spooler.yml
  playbooks/roles/guac_spooler/defaults/main.yml
Labels: fix

#985 add missing CSS for CycleCloud 8.2.2 static icons
  playbooks/roles/cyclecloud/files/fabric.css
  playbooks/roles/cyclecloud/tasks/main.yml
Labels: fix

#996 add a cloud init template script in the base packer image
  packer/base-centos79-v2-rdma.json
  packer/scripts/cloud_init.yml
Labels: kind/feature

#1000 Lustre is an optional block
  .github/workflows/configs/integration.yml
  .github/workflows/configs/lustre.yml
  .github/workflows/main.yml
  .github/workflows/main_callable.yml
  .github/workflows/openpbs.yml
  .github/workflows/openpbs_weekly.yml
  .github/workflows/slurm.yml
  .github/workflows/slurm_weekly.yml
  config.tpl.yml
  docs/deploy/define_environment.md
  install.sh
  playbooks/chrony.yml
  playbooks/guac_spooler.yml
  playbooks/lustre.yml
  playbooks/ood.yml
  playbooks/roles/chrony/tasks/main.yml
  playbooks/roles/cyclecloud_cluster/tasks/main.yml
  playbooks/telegraf.yml
  tf/lustre.tf
  tf/outputs.tf
  tf/variables_local.tf
Labels: kind/feature

#1006 Fix MODULEPATH for HPC CentOS image
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/5-default.sh.j2
Labels: fix

#1009 removed per-partition enroot enable switches
  config.tpl.yml
  docs/deploy/define_environment.md
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
  tutorials/lab1/config.tpl.yml
Labels: kind/feature

#1014 use Standard_D8s_v5 for viz node as we run on gen2 image
  .github/workflows/configs/integration.yml
  config.tpl.yml
  docs/deploy/define_environment.md
Labels: fix

#1015 Parameterize GUAC SPOOLER
  playbooks/ood-overrides-common.yml
  playbooks/roles/guac_spooler/defaults/main.yml
  playbooks/roles/guac_spooler/tasks/main.yml
Labels: kind/feature
