Repository Azure/az-hop, pull requests merged in 2023-06, with the labels that each got.

#1567 fix ssh port NSG when using Public IP
  bicep/azhop.bicep
Labels: fix

#1572 exit on failure when installing VirtualGL
  packer/scripts/centos/interactive-desktop-3d.sh
Labels: fix

#1577 only failed if vglserver_config is failing
  packer/scripts/centos/interactive-desktop-3d.sh
Labels: fix

#1581 report the NHC error before dying
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/99-healthcheck.sh
Labels: fix

#1585 local users in local admin group are also sudoers
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2
Labels: fix

#1587 bugfix in configure_ad.py
  playbooks/roles/cyclecloud/files/configure_ad.py
Labels: fix

#1562 Support Ubuntu on ccportal
  bicep/azhop.bicep
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  playbooks/ccportal.yml
  playbooks/roles/cyclecloud/tasks/CentOS.yml
  playbooks/roles/cyclecloud/tasks/Ubuntu.yml
  playbooks/roles/cyclecloud/tasks/main.yml
  playbooks/roles/telegraf/tasks/main.yml
  tf/ccportal.tf
  tf/variables_local.tf
Labels: kind/feature

#1589 fix ansible version to be 7.6.0
  toolset/scripts/requirements.txt
Labels: fix

#1600 Fix options.json packer script generated by Bicep
  bicep/azhop.bicep
Labels: fix

#1601 remove hardcoded default group for local users
  playbooks/create_local_user.yml
Labels: fix

#1602 Grafana, Telegraf, InfluxDB optional
  .github/workflows/all_bicep.yml
  .github/workflows/all_manual.yml
  .github/workflows/configs/base.yml
  .github/workflows/configs/integration.yml
  .github/workflows/configs/monitor_ama.yml
  .github/workflows/configs/monitor_grafana.yml
  .github/workflows/configs/monitor_none.yml
  .github/workflows/deploy_daily.yml
  .github/workflows/z_base_callable.yml
  .github/workflows/z_create_config_callable.yml
  .github/workflows/z_deploy_only_callable.yml
  bicep/azhop.bicep
  bicep/network.bicep
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  install.sh
  marketplace/solution/marketplace_config.yml
  playbooks/roles/cyclecloud_cluster/tasks/main.yml
  playbooks/roles/ood-applications/defaults/main.yml
  tests/configs/config_full.yml
  tf/grafana.tf
  tf/outputs.tf
  tf/templates/inventory.tmpl
  tf/variables_local.tf
Labels: kind/feature, area/monitoring

#1606 deprecate install_agent property in the config file schema
  config.schema.json
Labels: fix

#1610 fix Grafana version to 9.5.3
  playbooks/roles/grafana/tasks/install.yml
  playbooks/roles/grafana/tasks/main.yml
  playbooks/roles/grafana/vars/main.yml
Labels: fix

#1611 don't automatically upgrade grafana
  playbooks/grafana.yml
Labels: fix

#1617 override ood_core only when using winviz an with ood 2.0.29
  playbooks/ood.yml
Labels: kind/feature

#1618 slurm property in config file is optional
  bicep/azhop.bicep
  config.schema.json
Labels: fix

#1619 Fixes for minor code scan issues
  docs/_layouts/default.html
  playbooks/roles/cyclecloud/files/configure.py
  playbooks/roles/ood-applications/files/bc_amlsdk/template/after.sh.erb
  playbooks/roles/ood-applications/files/bc_jupyter/template/after.sh.erb
  playbooks/roles/ood-applications/files/bc_rstudio/template/after.sh.erb
  playbooks/roles/ood-applications/files/dashboard/app/models/active_jobs/jobstatusdata.rb
  playbooks/roles/pbsserver/files/submit-hook.py
Labels: fix

#1620 Update to CycleCloud version 8.4
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  playbooks/ccportal.yml
  playbooks/roles/cyclecloud/files/cyclecloud-slurm.txt
  playbooks/roles/cyclecloud/tasks/main.yml
  playbooks/roles/cyclecloud_cluster/vars/main.yml
  playbooks/roles/pbsserver/tasks/main.yml
  playbooks/roles/pbsserver/vars/main.yml
  playbooks/roles/slurmserver/defaults/main.yml
  playbooks/roles/slurmserver/tasks/main.yml
  playbooks/scheduler.yml
  tests/configs/config_full.yml
Labels: kind/feature

#1631 use Ansible import_tasks as import is deprecated
  playbooks/add_users.yml
  playbooks/remove_users.yml
  playbooks/roles/grafana/tasks/main.yml
Labels: kind/feature

#1635 use job composer and paraview application in the quickstart tutorial
  docs/tutorials/quickstart.md
  playbooks/files/ood_templates/slurm/eeesi_openfoam_tutorial/submit.sh
Labels: kind/feature
