Repository Azure/az-hop, pull requests merged in 2023-10, with the labels that each got.

#1704 remove empty metadata properties in private DNS zone bicep file
  bicep/privatezone_records.bicep
Labels: fix

#1711 update yq version to v4.35.2
  playbooks/ood.yml
  toolset/scripts/azhop-dependencies.yml
Labels: kind/feature

#1713 yum update all on jumpbox
  playbooks/linux.yml
Labels: fix

#1667 configurable resource names for infra VMs
  .github/workflows/configs/auth_ad.yml
  .github/workflows/configs/base.yml
  bicep/azhop.bicep
  bicep/cleanup.sh
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  package.json
  playbooks/cccluster.yml
  playbooks/grafana.yml
  playbooks/lustre.yml
  playbooks/nodearray_lookup.yml
  playbooks/ood-overrides-common.yml
  playbooks/ood.yml
  playbooks/roles/cyclecloud_cluster/projects/openpbs/cluster-init/scripts/2-installpbs.sh.j2
  playbooks/roles/grafana/tasks/main.yml
  playbooks/roles/grafana/templates/apache.json.j2
  playbooks/roles/grafana/templates/azhop_infra_servers.json.j2
  playbooks/roles/ood-applications/files/grafana/app.py
  playbooks/roles/ood-applications/tasks/main.yml
  playbooks/roles/pbsserver/tasks/main.yml
  playbooks/roles/slurmserver/tasks/main.yml
  playbooks/roles/slurmserver/templates/slurm.conf.j2
  playbooks/roles/slurmserver/templates/slurmdbd.conf.j2
  playbooks/telegraf.yml
  tests/readme.md
  tf/ad.tf
  tf/ccportal.tf
  tf/grafana.tf
  tf/jumpbox.tf
  tf/ondemand.tf
  tf/private_dns.tf
  tf/scheduler.tf
  tf/variables_local.tf
Labels: kind/feature, area/configuration, customer-requirement

#1714 Update packages and reboot if needed
  playbooks/ccportal.yml
  playbooks/grafana.yml
  playbooks/linux.yml
  playbooks/ood.yml
  playbooks/roles/cyclecloud/tasks/AlmaLinux.yml
  playbooks/roles/cyclecloud/tasks/CentOS.yml
  playbooks/roles/pkg_update/tasks/AlmaLinux.yml
  playbooks/roles/pkg_update/tasks/CentOS.yml
  playbooks/roles/pkg_update/tasks/Ubuntu.yml
  playbooks/roles/pkg_update/tasks/main.yml
  playbooks/roles/pkg_update/vars/main.yml
  playbooks/roles/slurmserver/tasks/main.yml
  playbooks/scheduler.yml
Labels: kind/feature

#1717 OpenPBS: set missing ccportal_name variable
  playbooks/roles/pbsserver/vars/main.yml
Labels: fix

#1719 remove ubuntu 18 support
  .github/workflows/configs/almalinux.yml
  .github/workflows/configs/centos.yml
  .github/workflows/configs/images.yml
  .github/workflows/configs/integration.yml
  .github/workflows/configs/minimum.yml
  .github/workflows/main_callable.yml
  .github/workflows/z_create_config_callable.yml
  config.tpl.yml
  docs/deploy/index.md
  packer/azhop-compute-ubuntu-18_04.json
Labels: kind/feature

#1715 Support for Azure Managed Lustre File System
  .github/workflows/configs/base.yml
  .github/workflows/configs/lustre.yml
  .github/workflows/slurm.yml
  bicep/amlfs.bicep
  bicep/azhop.bicep
  bicep/install.sh
  build.sh
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  docs/tutorials/Implementing_Azure_HPC_OnDemand_Platform.md
  install.sh
  marketplace/solution/lustreCapacity.uidef
  marketplace/solution/marketplace_config.yml
  marketplace/solution/ui_definition.json
  playbooks/lustre-sas.yml
  playbooks/lustre.yml
  playbooks/ood.yml
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/2-mountlustre.sh.j2
  playbooks/roles/grafana/dashboards/lustre-and-hsm.json
  playbooks/roles/lustre/defaults/main.yml
  playbooks/roles/lustre/tasks/client.yml
  playbooks/roles/lustre/tasks/configure_client.yml
  playbooks/roles/lustre/tasks/configure_server.yml
  playbooks/roles/lustre/tasks/main.yml
  playbooks/roles/lustre/tasks/mds.yml
  playbooks/roles/lustre/tasks/oss.yml
  playbooks/roles/lustre/tasks/repos.yml
  playbooks/roles/lustre/tasks/robinhood.yml
  playbooks/roles/lustre/templates/lhsm-plugin-az.j2
  playbooks/roles/lustre/templates/lhsmd.service.j2
  playbooks/roles/lustre/templates/lustre.conf.j2
  playbooks/roles/ood-applications/defaults/main.yml
  playbooks/roles/ood-applications/files/robinhood/app.py
  playbooks/roles/ood-applications/files/robinhood/manifest.yml
  playbooks/roles/ood-applications/files/robinhood/passenger_wsgi.py
  tf/lustre.tf
  tf/outputs.tf
  tf/templates/global_variables.tmpl
  tf/templates/inventory.cis.tmpl
  tf/templates/inventory.tmpl
  tf/variables_local.tf
Labels: kind/feature, breaking-change

#1724 Update default CycleCloud to version 8.4.2-3186
  config.tpl.yml
  docs/deploy/index.md
  playbooks/ccportal.yml
  playbooks/roles/cyclecloud/defaults/all.yml
  playbooks/roles/cyclecloud/defaults/main.yml
  playbooks/roles/cyclecloud/tasks/AlmaLinux.yml
  playbooks/roles/cyclecloud/tasks/CentOS.yml
  playbooks/roles/cyclecloud/tasks/Ubuntu.yml
  playbooks/roles/cyclecloud/tasks/main.yml
  playbooks/scheduler.yml
Labels: kind/feature

#1726 Fix RStudio launcher with PBS
  playbooks/roles/ood-applications/files/bc_rstudio/template/start_container.sh
  playbooks/roles/ood-applications/files/bc_rstudio/template/start_rstudio.sh
Labels: fix

#1728 Allow to set OIDCStateMaxNumberOfCookies
  config.tpl.yml
  docs/deploy/index.md
  playbooks/ood-overrides-auth-oidc.yml
Labels: fix

#1734 upgrade miniconda packages
  toolset/scripts/install.sh
Labels: kind/feature

#1735 new marketplace UI
  marketplace/solution/marketplace_config.yml
  marketplace/solution/ui_definition.json
Labels: kind/feature

#1736 fix vmd app
  playbooks/roles/ood-applications/files/bc_vmd/template/script.sh.erb
  playbooks/roles/ood-applications/files/bc_vmd/template/xfce.sh
Labels: fix

#1737 Create a kiosk mode xfce launch script
  playbooks/roles/ood-applications/files/bc_ansys_workbench/template/script.sh.erb
  playbooks/roles/ood-applications/files/bc_ansys_workbench/template/xfce_kiosk.sh
  playbooks/roles/ood-applications/files/bc_paraview/template/script.sh.erb
  playbooks/roles/ood-applications/files/bc_paraview/template/xfce_kiosk.sh
  playbooks/roles/ood-applications/files/bc_vmd/template/script.sh.erb
  playbooks/roles/ood-applications/files/bc_vmd/template/xfce_kiosk.sh
  playbooks/roles/ood-applications/files/library/xfce_kiosk.sh
Labels: kind/feature

#1739 Assign NSG to netapp subnet
  bicep/azhop.bicep
  tf/network_security_group.tf
  tf/variables_local.tf
Labels: kind/feature

#1741 Resolve CycleCloud CLI installation on CentOS 79
  playbooks/roles/cyclecloud/tasks/CentOS.yml
  playbooks/roles/cyclecloud/tasks/main.yml
Labels: fix

#1742 fix ARM
  bicep/azhop.bicep
  build.sh
  marketplace/solution/ui_definition.json
Labels: fix

#1745 Reorganize default queues
  .github/workflows/configs/almalinux.yml
  .github/workflows/configs/centos.yml
  .github/workflows/configs/integration.yml
  .github/workflows/configs/minimum.yml
  config.tpl.yml
  docs/deploy/index.md
  docs/operate/manually_add_nodes.md
  docs/tutorials/Implementing_Azure_HPC_OnDemand_Platform.md
  docs/tutorials/containers.md
  docs/tutorials/opm.md
  docs/tutorials/osu_benchmarks.md
  docs/tutorials/quickstart.md
  docs/tutorials/spack.md
  examples/minimum_public_ip.yml
  examples/qinstall-config.yml
  marketplace/solution/marketplace_config.yml
  playbooks/files/ood_templates/openpbs/eeesi_openfoam_tutorial/submit.sh
  playbooks/files/ood_templates/openpbs/impi_pingpong/manifest.yml
  playbooks/files/ood_templates/openpbs/impi_pingpong/pingpong.sh
  playbooks/files/ood_templates/openpbs/impi_ring_pingpong/manifest.yml
  playbooks/files/ood_templates/openpbs/impi_ring_pingpong/ring_pingpong.sh
  playbooks/files/ood_templates/slurm/eeesi_openfoam_tutorial/submit.sh
  playbooks/files/ood_templates/slurm/impi_pingpong/manifest.yml
  playbooks/files/ood_templates/slurm/impi_pingpong/pingpong.sh
  playbooks/files/ood_templates/slurm/impi_ring_pingpong/manifest.yml
  playbooks/files/ood_templates/slurm/impi_ring_pingpong/ring_pingpong.sh
  playbooks/roles/pbsserver/files/doqmgr.sh
  tests/configs/config_full.yml
  tests/cyclecloud_home.spec.ts
  tests/ood_interactive_apps.spec.ts
  tutorials/lab1/config.tpl.yml
Labels: kind/feature
