Repository Azure/az-hop, pull requests merged in 2023-08, with the labels that each got.

#1652 Fix to allow marketplace deployment in AzureUSGovernment
  bicep/install.sh
Labels: fix

#1651 add a new tab to select which azhop applications will be installed at…
  marketplace/solution/marketplace_config.yml
  marketplace/solution/ui_definition.json
Labels: kind/feature

#1663 vizer: fix default container image tag
  playbooks/roles/ood-applications/files/bc_vizer/form.yml.erb
  playbooks/roles/ood-applications/files/bc_vizer/template/before.sh.erb
Labels: area/application, fix

#1666 install code-server to resource disk
  playbooks/roles/ood-applications/files/bc_codeserver/template/script.sh.erb
Labels: kind/feature

#1668 update packages for security
  packer/scripts/almalinux/interactive-desktop-3d.sh
  packer/scripts/almalinux/linux-setup.sh
Labels: kind/feature
