Repository Azure/az-hop, pull requests merged in 2023-09, with the labels that each got.

#1671 Deprecate Windows Remote Viz
  .github/workflows/all_bicep.yml
  .github/workflows/all_manual.yml
  .github/workflows/configs/base.yml
  .github/workflows/configs/integration.yml
  .github/workflows/configs/winviz.yml
  .github/workflows/main_callable.yml
  .github/workflows/z_base_callable.yml
  .github/workflows/z_create_config_callable.yml
  .github/workflows/z_deploy_only_callable.yml
  bicep/azhop.bicep
  config.schema.json
  config.tpl.yml
  docs/apps/index.md
  docs/deploy/index.md
  docs/operate/alerting.md
  docs/operate/how_to.md
  docs/tutorials/Implementing_Azure_HPC_OnDemand_Platform.md
  install.sh
  marketplace/solution/marketplace_config.yml
  packer/azhop-win10.json
  packer/scripts/windows/install-choco.ps1
  packer/scripts/windows/optimize.ps1
  packer/scripts/windows/sysprep.ps1
  packer/scripts/windows/wait-for-agent.ps1
  playbooks/cccluster.yml
  playbooks/guac_spooler.yml
  playbooks/guacamole.yml
  playbooks/ood-overrides-common.yml
  playbooks/ood-overrides-guacamole.yml
  playbooks/ood.yml
  playbooks/roles/cyclecloud_cluster/defaults/all.yml
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/windows/4-configure-rdp.bat
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.bat.j2
  playbooks/roles/cyclecloud_cluster/tasks/common.yml
  playbooks/roles/cyclecloud_cluster/tasks/main.yml
  playbooks/roles/cyclecloud_cluster/templates/azhop-remoteviz.txt.j2
  playbooks/roles/cyclecloud_cluster/vars/main.yml
  playbooks/roles/grafana/dashboards/azhop_infra_servers.json
  playbooks/roles/guac_spooler/defaults/main.yml
  playbooks/roles/guac_spooler/tasks/main.yml
  playbooks/roles/guac_spooler/vars/main.yml
  playbooks/roles/ood-applications/defaults/main.yml
  playbooks/roles/ood-applications/files/bc_guacamole/form.yml
  playbooks/roles/ood-applications/files/bc_guacamole/manifest.yml
  playbooks/roles/ood-applications/files/bc_guacamole/submit.yml.erb
  playbooks/roles/ood-applications/files/bc_guacamole/template/after.sh.erb
  playbooks/roles/ood-applications/files/bc_guacamole/template/script.sh.erb
  playbooks/roles/ood-applications/files/bc_guacamole/view.html.erb
  playbooks/roles/ood-applications/files/dashboard/app/models/active_jobs/jobstatusdata.rb
  tests/configs/config_full.yml
  tf/guacamole.tf
  tf/mariadb.tf
  tf/outputs.tf
  tf/templates/inventory.tmpl
  tf/variables_local.tf
Labels: kind/feature, breaking-change

#1673 New defaults for the marketplace deployment
  marketplace/solution/ui_definition.json
Labels: kind/feature

#1674 switch to cyclecloud-slurm 2.7.2 by default
  config.schema.json
  config.tpl.yml
  playbooks/roles/cyclecloud/files/cyclecloud-slurm.txt
  playbooks/roles/cyclecloud_cluster/vars/main.yml
  playbooks/roles/slurmserver/defaults/main.yml
Labels: kind/feature

#1677 use AlmaLinux by default when deploying with the Marketplace application
  marketplace/solution/marketplace_config.yml
Labels: kind/feature

#1681 fix domain join package list for AlmaLinux
  azhop_state.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/almalinux/init_joindomain.sh
  playbooks/roles/domain_join/tasks/main.yml
  playbooks/roles/domain_join/vars/AlmaLinux/8.yml
  playbooks/roles/domain_join/vars/CentOS/7.yml
Labels: fix

#1689 Fix noVNC session launch and ubuntu image creation
  packer/azhop-centos79-desktop3d-ci.json
  packer/azhop-centos79-desktop3d.json
  packer/azhop-centos79-v2-rdma-ci.json
  packer/azhop-centos79-v2-rdma-gpgpu.json
  packer/azhop-compute-almalinux-8_7-ci.json
  packer/azhop-compute-almalinux-8_7.json
  packer/azhop-compute-centos-7_9.json
  packer/azhop-compute-ubuntu-18_04.json
  packer/azhop-compute-ubuntu-20_04.json
  packer/azhop-desktop-almalinux-8_7.json
  packer/azhop-desktop-centos-7_9-gen1.json
  packer/azhop-desktop-centos-7_9.json
  packer/azhop-desktop-ubuntu-20_04.json
  packer/base-centos79-v2-rdma.json
  packer/build_image.sh
  packer/scripts/centos/interactive-desktop-3d.sh
  packer/scripts/ubuntu/lustreclient.sh
Labels: fix

#1693 Fix launching RSTUDIO with openpbs
  playbooks/roles/ood-applications/files/bc_rstudio/template/before.sh.erb
  playbooks/roles/ood-applications/files/bc_rstudio/template/start_container.sh
  playbooks/roles/ood-applications/files/bc_rstudio/template/start_rstudio.sh
Labels: fix

#1690 Documentation on default azhop images
  docs/operate/index.md
  docs/operate/marketplace_images.md
Labels: documentation

#1695 added import and state TF commands
  build.sh
Labels: kind/feature
