Repository Azure/az-hop, pull requests merged in 2023-02, with the labels that each got.

#1309 application integration documentation
  docs/apps/index.md
  docs/index.md
Labels: kind/feature

#1316 add time unit for clarification
  playbooks/roles/ood-applications/files/bc_codeserver/form.yml.erb
  playbooks/roles/ood-applications/files/bc_guacamole/form.yml
  playbooks/roles/ood-applications/files/bc_jupyter/form.yml.erb
Labels: kind/feature

#1326 disable reverse dns for kerberos to enable domain join
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/ubuntu/init_joindomain.sh
Labels: fix

#1327 [Bicep] MariaDB in US Gov, SIG optional
  config.tpl.yml
  deploy/purebicep/azhop.bicep
  deploy/purebicep/build.sh
  deploy/purebicep/keyvault.bicep
  deploy/purebicep/mainTemplate.bicep
  deploy/purebicep/mariadb.bicep
Labels: kind/feature

#1331 Configure output as json to avoid errors
  build.sh
Labels: fix

#1305 Use System Managed Identity instead of User Managed Identity
  tf/ccportal.tf
  tf/guacamole.tf
  tf/lustre.tf
Labels: kind/feature

#1335 Allow SLURM cluster name to be set through the configuration file
  config.tpl.yml
  playbooks/roles/slurmserver/tasks/accounting.yml
  playbooks/roles/slurmserver/tasks/main.yml
  playbooks/roles/slurmserver/templates/slurm.conf.j2
Labels: kind/feature

#1317 add interactive app: paraview
  config.tpl.yml
  playbooks/roles/ood-applications/defaults/main.yml
  playbooks/roles/ood-applications/files/bc_paraview/form.yml.erb
  playbooks/roles/ood-applications/files/bc_paraview/icon.png
  playbooks/roles/ood-applications/files/bc_paraview/manifest.yml
  playbooks/roles/ood-applications/files/bc_paraview/readme.md
  playbooks/roles/ood-applications/files/bc_paraview/submit.yml.erb
  playbooks/roles/ood-applications/files/bc_paraview/template/before.sh.erb
  playbooks/roles/ood-applications/files/bc_paraview/template/config/menus/xfce-applications.menu
  playbooks/roles/ood-applications/files/bc_paraview/template/config/xfce4/terminal/terminalrc
  playbooks/roles/ood-applications/files/bc_paraview/template/config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
  playbooks/roles/ood-applications/files/bc_paraview/template/script.sh.erb
  playbooks/roles/ood-applications/tasks/main.yml
  playbooks/roles/ood-applications/tasks/paraview.yml
Labels: kind/feature

#1341 [Bicep] - Use System Managed Identity instead of User Managed Identity
  .github/workflows/configs/integration.yml
  .github/workflows/configs/lustre.yml
  .github/workflows/main_callable.yml
  config.tpl.yml
  deploy/purebicep/azhop.bicep
  deploy/purebicep/build.sh
  deploy/purebicep/install.sh
  deploy/purebicep/roleAssignments.bicep
  deploy/purebicep/vm.bicep
  install.sh
  playbooks/ood.yml
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/nhc_common.conf.j2
  playbooks/roles/cyclecloud_cluster/tasks/main.yml
  playbooks/roles/ood-applications/defaults/main.yml
  playbooks/tests.yml
  tf/variables_local.tf
Labels: kind/feature, breaking-change

#1346 standalone installation of codeserver to allow usage for non sudo users
  playbooks/roles/ood-applications/files/bc_codeserver/template/script.sh.erb
Labels: fix

#1345 set default user for bin/connect
  tf/templates/connect.tmpl
Labels: kind/feature

#1347 added --dry-run option to the bicep build script
  deploy/purebicep/build.sh
Labels: kind/feature, area/bicep

#1350 [Bicep] Support ANF and Azure Files
  .github/workflows/configs/integration.yml
  .github/workflows/main.yml
  .github/workflows/main_callable.yml
  config.tpl.yml
  deploy/purebicep/anf.bicep
  deploy/purebicep/azhop.bicep
  deploy/purebicep/cleanup.sh
  docs/deploy/index.md
Labels: kind/feature, area/bicep

#1353 generic: add schema for config.yml
  build.sh
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  toolset/scripts/install.sh
Labels: do-not-merge, kind/feature

#1334 New toolchain install script
  .github/workflows/build_image_callable.yml
  .github/workflows/main_callable.yml
  .github/workflows/marketplace_image.yml
  .github/workflows/uitesting_callable.yml
  .gitignore
  build.sh
  install.sh
  playbooks/cccluster.yml
  toolset/Dockerfile
  toolset/scripts/azhop-dependencies.yml
  toolset/scripts/install.sh
  toolset/scripts/install.sh.bak
  toolset/scripts/requirements.txt
  toolset/scripts/requirements.yml
Labels: kind/feature

#1362 new exhaustive configuration file schema
  .github/workflows/configs/integration.yml
  build.sh
  config.schema.json
  install.sh
  tests/configs/config_full.yml
  validate_config.sh
Labels: kind/feature

#1344 vizer: a paraview/trame based web application
  config.tpl.yml
  docs/images/vizer_launch_form.png
  docs/images/vizer_session.png
  docs/user_guide/index.md
  docs/user_guide/vizer.md
  playbooks/roles/ood-applications/defaults/main.yml
  playbooks/roles/ood-applications/files/bc_vizer/form.js
  playbooks/roles/ood-applications/files/bc_vizer/form.yml.erb
  playbooks/roles/ood-applications/files/bc_vizer/icon.png
  playbooks/roles/ood-applications/files/bc_vizer/manifest.yml
  playbooks/roles/ood-applications/files/bc_vizer/readme.md
  playbooks/roles/ood-applications/files/bc_vizer/submit.yml.erb
  playbooks/roles/ood-applications/files/bc_vizer/template/before.sh.erb
  playbooks/roles/ood-applications/files/bc_vizer/template/get_container.sh
  playbooks/roles/ood-applications/files/bc_vizer/template/script.sh.erb
  playbooks/roles/ood-applications/files/bc_vizer/view.html.erb
  playbooks/roles/ood-applications/tasks/main.yml
  playbooks/roles/ood-applications/tasks/vizer.yml
Labels: kind/feature

#1367 create DNS forwarder rules only if defined in the config file
  tf/private_dns_resolver.tf
  tf/variables_local.tf
Labels: fix

#1369 use archive URL for guacamole
  playbooks/guacamole.yml
Labels: fix

#1373 fix wrong create subnet flags when creating NSG on existing subnets
  tf/network_security_group.tf
  tf/outputs.tf
Labels: fix

#1374 Schema update - added deployer VM and vizer app
  .github/workflows/configs/integration.yml
  config.schema.json
Labels: kind/feature
