Repository Azure/az-hop, pull requests merged in 2023-05, with the labels that each got.

#1495 Disable lustre by default
  .github/workflows/main.yml
  .github/workflows/main_callable.yml
  config.tpl.yml
  docs/deploy/index.md
Labels: kind/feature

#1497 rotate MariaDB certificate
  playbooks/guacamole.yml
  playbooks/roles/guac_spooler/tasks/main.yml
  playbooks/roles/slurmserver/tasks/accounting.yml
  playbooks/roles/slurmserver/templates/slurmdbd.conf.j2
Labels: kind/feature

#1498 document role needed when using an existing Log Analytics Workspace
  config.tpl.yml
  docs/deploy/index.md
Labels: fix

#1501 add documentation explaining how to deploy with bicep
  docs/deploy/index.md
Labels: kind/feature

#1454 Connect to an existing Domain Controller
  .github/workflows/configs/integration.yml
  bicep/azhop.bicep
  bicep/keyvault.bicep
  bicep/kv_secrets.bicep
  bicep/network.bicep
  bicep/secrets.bicep
  build.sh
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  install.sh
  playbooks/ad.yml
  playbooks/add_users.yml
  playbooks/cccluster.yml
  playbooks/create_user.yml
  playbooks/files/pun_pre_hook.sh
  playbooks/grafana.yml
  playbooks/guac_spooler.yml
  playbooks/init_user.yml
  playbooks/linux.yml
  playbooks/nodearray_lookup.yml
  playbooks/ood-overrides-common.yml
  playbooks/ood.yml
  playbooks/remove_users.yml
  playbooks/roles/cyclecloud/tasks/main.yml
  playbooks/roles/cyclecloud_cluster/defaults/all.yml
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/windows/4-configure-rdp.bat
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.bat.j2
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/5-default.sh.j2
  playbooks/roles/domain_join/tasks/main.yml
  playbooks/roles/domain_join/vars/main.yml
  playbooks/roles/grafana/tasks/configure.yml
  playbooks/roles/grafana/templates/ldap.toml.j2
  playbooks/templates/user_record.txt.j2
  tests/configs/config_full.yml
  tf/active_directory/monitor.tf
  tf/active_directory/outputs.tf
  tf/ad.tf
  tf/anf.tf
  tf/keyvault.tf
  tf/network.tf
  tf/network_security_group.tf
  tf/outputs.tf
  tf/private_dns.tf
  tf/templates/global_variables.tmpl
  tf/templates/inventory.tmpl
  tf/variables_local.tf
Labels: kind/feature

#1476 Support User assigned Managed Identity for the deployer VM
  build.sh
  docs/deploy/index.md
Labels: kind/feature

#1506 Support Azure NFS Files as home directory
  bicep/azhop.bicep
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  tf/anf.tf
  tf/azurefiles.tf
  tf/network.tf
  tf/outputs.tf
  tf/variables_local.tf
Labels: kind/feature

#1504 Simplified configuration and examples
  bicep/azhop.bicep
  bicep/vm.bicep
  config.schema.json
  config.tpl.yml
  examples/index.md
  examples/minimum_public_ip.yml
  tf/outputs.tf
  tf/sig.tf
  tf/variables_local.tf
Labels: kind/feature

#1514 fix wrong TF logic when building AD with domain specified in the config file
  config.tpl.yml
  docs/deploy/index.md
  tf/ad.tf
  tf/outputs.tf
Labels: fix

#1516 fix build lustre cluster when lustre.create is false
  tf/lustre.tf
  tf/templates/inventory.tmpl
  tf/variables_local.tf
Labels: fix

#1518 Terraform : don't create ANF if anf.create is false
  config.schema.json
  tf/variables_local.tf
Labels: fix

#1520 Create AD Domain - remove automatic retries
  playbooks/ad.yml
Labels: fix

#1522 fix wrong destination for the SSL cert
  playbooks/roles/guac_spooler/tasks/main.yml
Labels: fix

#1524 make windows remoteviz fully optional
  playbooks/cccluster.yml
Labels: fix

#1528 generic: fix install.sh for ansible tags
  install.sh
Labels: fix

#1530 Fix for grafana login problem
  playbooks/roles/grafana/templates/ldap.toml.j2
Labels: fix

#1540 fix ldap server in cyclecloud ansible role
  playbooks/roles/cyclecloud/tasks/main.yml
Labels: fix

#1548 fix default settings for min/max hours of viz nodes
  playbooks/ood-overrides-common.yml
  playbooks/ood.yml
Labels: fix

#1550 Fix wrong domain join user for guacamole
  playbooks/guac_spooler.yml
Labels: fix

#1552 Initialize OOD application when needed
  playbooks/roles/ood-applications/defaults/main.yml
  playbooks/roles/ood-applications/tasks/main.yml
Labels: kind/feature

#1551 increase mariadb backup retention to 35 days (max)
  bicep/mariadb.bicep
  tf/mariadb.tf
Labels: kind/feature

#1535 Add support for local users
  bicep/azhop.bicep
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  install.sh
  playbooks/add_local_users.yml
  playbooks/cccluster.yml
  playbooks/create_local_user.yml
  playbooks/create_local_user_cc.yml
  playbooks/grafana.yml
  playbooks/linux.yml
  playbooks/roles/cyclecloud/tasks/main.yml
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/nhc_common.conf.j2
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3a-add-users.sh.j2
  playbooks/roles/cyclecloud_cluster/tasks/main.yml
  playbooks/roles/grafana/templates/grafana.ini.j2
  playbooks/templates/local_user_record.txt.j2
  tf/ad.tf
  tf/keyvault.tf
  tf/private_dns.tf
  tf/variables_local.tf
Labels: area/user-management, kind/feature, area/active directory

#1553 pin the Shell Access application on the home page
  playbooks/ood-overrides-common.yml
Labels: kind/feature

#1556 Bicep : add userAuth variable with default value to ad
  bicep/azhop.bicep
Labels: fix

#1544 Config.yml settings for resource names
  bicep/azhop.bicep
  bicep/keyvault.bicep
  bicep/mariadb.bicep
  bicep/storage.bicep
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  tf/keyvault.tf
  tf/main.tf
  tf/mariadb.tf
  tf/variables_local.tf
Labels: kind/feature, area/configuration

#1558 Improve ADDS installation
  playbooks/ad.yml
Labels: fix

#1557 Bugfix eessi openfoam
  playbooks/files/ood_templates/slurm/eeesi_openfoam_tutorial/submit.sh
Labels: fix

#1560 activate miniconda and check if packer file exists
  packer/build_image.sh
Labels: fix

#1561 Remote Desktop : When using the whole machine set PBS to use all cores
  playbooks/ood-overrides-openpbs.yml
Labels: kind/feature
