Repository Azure/az-hop, pull requests merged in 2023-03, with the labels that each got.

#1383 Gracefully migrate Key Vault roles of VMs using System Managed Identity
  tf/guacamole.tf
  tf/lustre.tf
Labels: fix

#1392 enable enroot by default in config
  config.tpl.yml
  docs/deploy/index.md
  tests/configs/config_full.yml
Labels: kind/feature

#1384 add rstudio app
  .github/workflows/configs/integration.yml
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  playbooks/roles/ood-applications/files/bc_rstudio/LICENSE.txt
  playbooks/roles/ood-applications/files/bc_rstudio/README.md
  playbooks/roles/ood-applications/files/bc_rstudio/form.yml.erb
  playbooks/roles/ood-applications/files/bc_rstudio/icon.png
  playbooks/roles/ood-applications/files/bc_rstudio/manifest.yml
  playbooks/roles/ood-applications/files/bc_rstudio/submit.yml.erb
  playbooks/roles/ood-applications/files/bc_rstudio/template/after.sh.erb
  playbooks/roles/ood-applications/files/bc_rstudio/template/before.sh.erb
  playbooks/roles/ood-applications/files/bc_rstudio/template/get_container.sh
  playbooks/roles/ood-applications/files/bc_rstudio/template/script.sh.erb
  playbooks/roles/ood-applications/files/bc_rstudio/template/start_container.sh
  playbooks/roles/ood-applications/files/bc_rstudio/template/start_rstudio.sh
  playbooks/roles/ood-applications/files/bc_rstudio/view.html.erb
Labels: kind/feature

#1265 Monitoring and alerting via azure monitor agent
  .github/workflows/configs/integration.yml
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  docs/operate/alerting.md
  docs/operate/index.md
  tests/configs/config_full.yml
  tf/anf.tf
  tf/ccportal.tf
  tf/grafana.tf
  tf/guacamole.tf
  tf/jumpbox.tf
  tf/monitor.tf
  tf/ondemand.tf
  tf/scheduler.tf
  tf/variables_local.tf
Labels: kind/feature, area/monitoring

#1379 update enroot version to 3.4.1 in the images
  packer/scripts/almalinux/slurm.sh
  packer/scripts/centos/slurm.sh
  packer/scripts/ubuntu/slurm.sh
Labels: kind/feature, area/container

#1398 bump pyxis version to 0.15.0
  playbooks/roles/slurmserver/defaults/main.yml
Labels: kind/feature, area/container, area/slurm

#1397 install amlfs lustre client on the ondemand node
  playbooks/roles/lustre/tasks/configure_client.yml
Labels: kind/feature, area/ood, area/lustre

#1402 automatic sssd restart in case of failure
  playbooks/roles/domain_join/handlers/main.yml
  playbooks/roles/domain_join/tasks/main.yml
Labels: fix

#1403 Enroot update
  .github/workflows/configs/integration.yml
  config.schema.json
  config.tpl.yml
  deploy/purebicep/azhop.bicep
  deploy/resources/azhop-config-templates/config.yml.j2
  docs/deploy/index.md
  docs/tutorials/containers.md
  playbooks/cccluster.yml
  playbooks/ood.yml
  playbooks/roles/cyclecloud_cluster/projects/enroot/cluster-init/scripts/2-install_enroot.sh.j2
  playbooks/roles/cyclecloud_cluster/tasks/main.yml
  playbooks/roles/cyclecloud_cluster/templates/azhop-OpenPBS.txt.j2
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
  playbooks/roles/slurmclient/tasks/main.yml
  playbooks/roles/slurmserver/tasks/main.yml
  playbooks/scheduler.yml
  tests/configs/config_full.yml
Labels: kind/feature, area/container

#1408 do not install lustre client on robinhood
  playbooks/roles/lustre/tasks/main.yml
Labels: fix

#1412 close socks tunnel before starting a new one
  playbooks/add_users.yml
Labels: fix

#1414 Fix for issue with slurm on ubuntu18 (unable to find su binary)
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/5-default.sh.j2
Labels: kind/bug, fix, area/slurm

#1337 Jupyter Notebook integration with Azure ML SDK
  config.tpl.yml
  playbooks/roles/ood-applications/defaults/main.yml
  playbooks/roles/ood-applications/files/bc_amlsdk/form.yml.erb
  playbooks/roles/ood-applications/files/bc_amlsdk/icon.png
  playbooks/roles/ood-applications/files/bc_amlsdk/images/azhopamlsdkscreen1.png
  playbooks/roles/ood-applications/files/bc_amlsdk/images/azhopamlsdkscreen2.png
  playbooks/roles/ood-applications/files/bc_amlsdk/images/azhopamlsdkscreen3.png
  playbooks/roles/ood-applications/files/bc_amlsdk/manifest.yml
  playbooks/roles/ood-applications/files/bc_amlsdk/readme.md
  playbooks/roles/ood-applications/files/bc_amlsdk/submit.yml.erb
  playbooks/roles/ood-applications/files/bc_amlsdk/template/after.sh.erb
  playbooks/roles/ood-applications/files/bc_amlsdk/template/amlwrapperfunctions.py
  playbooks/roles/ood-applications/files/bc_amlsdk/template/azure-ml.svg
  playbooks/roles/ood-applications/files/bc_amlsdk/template/before.sh.erb
  playbooks/roles/ood-applications/files/bc_amlsdk/template/get_container.sh
  playbooks/roles/ood-applications/files/bc_amlsdk/template/nbbuilder.py
  playbooks/roles/ood-applications/files/bc_amlsdk/template/script.sh.erb
  playbooks/roles/ood-applications/files/bc_amlsdk/template/start_container.sh
  playbooks/roles/ood-applications/files/bc_amlsdk/template/start_jupyter.sh
  playbooks/roles/ood-applications/files/bc_amlsdk/view.html.erb
Labels: kind/feature

#1419 use wget to avoid SSL error when downloading Baltimore certificate
  playbooks/guacamole.yml
  playbooks/roles/guac_spooler/tasks/main.yml
  playbooks/roles/slurmserver/tasks/accounting.yml
Labels: fix

#1421 update all packages with latest version
  playbooks/ccportal.yml
  playbooks/grafana.yml
  playbooks/guac_spooler.yml
  playbooks/linux.yml
  playbooks/roles/lustre/tasks/main.yml
  playbooks/scheduler.yml
Labels: kind/feature

#1417 enable use of an existing log analytics workspace
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  tf/ccportal.tf
  tf/grafana.tf
  tf/guacamole.tf
  tf/jumpbox.tf
  tf/monitor.tf
  tf/ondemand.tf
  tf/scheduler.tf
  tf/variables_local.tf
Labels: kind/feature

#1445 install apptainer
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/almalinux/init_apptainer.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/centos/init_apptainer.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/ubuntu/init_apptainer.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/9-apptainer.sh
Labels: kind/feature, area/application

#1451 Added OpenFOAM example submission and Log Viewer
  playbooks/files/ood_templates/slurm/eeesi_openfoam_tutorial/manifest.yml
  playbooks/files/ood_templates/slurm/eeesi_openfoam_tutorial/submit.sh
  playbooks/roles/ood-applications/files/bc_jupyter/template/OFLogView.ipynb
  playbooks/roles/ood-applications/files/bc_jupyter/template/OFLogView.svg
  playbooks/roles/ood-applications/files/bc_jupyter/template/start_jupyter.sh
Labels: kind/feature
