Repository Azure/az-hop, pull requests merged in 2023-11, with the labels that each got.

#1753 fix for issue in some hpc images causing lustre performance degradation
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/2-mountlustre.sh.j2
Labels: fix

#1721 Feature/cluster dashboard
  config.schema.json
  config.tpl.yml
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/telegraf.conf.j2
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/4-install-telegraf.sh
  playbooks/roles/grafana/tasks/main.yml
  playbooks/roles/grafana/templates/azhop_compute_servers.json.j2
  playbooks/roles/grafana/templates/cluster-stats.json.j2
  playbooks/telegraf.yml
Labels: do-not-merge, kind/feature

#1754 Use external auth module (mod_authnz_external) for CycleCloud Proxy.
  playbooks/ood.yml
Labels: fix

#1757 Updates for Marketplace deployment
  docs/images/marketplace/az-hop-marketplace-applications.png
  docs/images/marketplace/az-hop-marketplace-basics.png
  docs/images/marketplace/az-hop-marketplace-directory.png
  docs/images/marketplace/az-hop-marketplace-lustre.png
  docs/images/marketplace/az-hop-marketplace-network.png
  docs/images/marketplace/az-hop-marketplace-other-settings.png
  docs/images/marketplace/az-hop-marketplace-slurm.png
  docs/tutorials/marketplace_deployment.md
Labels: area/administration

#1761 Use EphemeralOSDisk by default
  playbooks/roles/cyclecloud_cluster/templates/azhop-OpenPBS.txt.j2
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
Labels: kind/feature

#1763 Allow a max_count to be set for the maximum number of nodes
  .github/workflows/configs/almalinux.yml
  .github/workflows/configs/centos.yml
  .github/workflows/configs/integration.yml
  .github/workflows/configs/minimum.yml
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  playbooks/roles/cyclecloud_cluster/templates/azhop-OpenPBS.txt.j2
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
  playbooks/roles/tests/tasks/main.yml
Labels: kind/feature

#1765 use NHC from the HPC image
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/nhc_common.conf.j2
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/az-hop.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/csc_nvidia_smi.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/gpu_app_clocks.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/gpu_clock_throttling.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/gpu_ecc.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/gpu_persistence.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/nhc/scripts/gpu_xid.nhc
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/8-configure-nhc.sh
Labels: kind/feature

#1767 install packages for domain joining only when needed
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/almalinux/init_joindomain.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/centos/init_joindomain.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/ubuntu/init_joindomain.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2
Labels: kind/feature

#1769 Marketplace : Use version 3.0.4 for cyclecloud_slurm_version
  marketplace/solution/marketplace_config.yml
  marketplace/solution/ui_definition.json
Labels: kind/feature

#1759 remove weak protocols and ciphers from apache
  playbooks/ood.yml
Labels: kind/feature, kind/security, area/ood

#1758 Security feature: Configure max file upload size and allowed extensions
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  playbooks/ood-overrides-common.yml
  playbooks/ood.yml
Labels: kind/feature, kind/security, area/ood

#1772 Use mod_authnz_external for Apache authentication instead of PAM
  playbooks/ood-overrides-auth-basic.yml
  playbooks/ood.yml
Labels: kind/feature

#1774 dynamically set httpd_auth based on distro
  playbooks/ood-overrides-auth-basic.yml
  playbooks/ood.yml
Labels: fix

#1775 Add ood directory whitelist option
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  playbooks/ood-overrides-common.yml
Labels: kind/feature, kind/security, area/ood
