Repository Azure/az-hop, pull requests merged in 2024-01, with the labels that each got.

#1801 Automatically configure GPU count in integrated Open OnDemand applications
  config.schema.json
  playbooks/cccluster.yml
  playbooks/nodearray_lookup.yml
  playbooks/ood-overrides-slurm.yml
  playbooks/roles/cyclecloud_cluster/defaults/all.yml
  playbooks/roles/ood-applications/files/bc_ansys_workbench/submit.yml.erb
  playbooks/roles/ood-applications/files/bc_paraview/form.yml.erb
  playbooks/roles/ood-applications/files/bc_paraview/submit.yml.erb
  playbooks/roles/ood-applications/files/bc_paraview/template/script.sh.erb
  playbooks/roles/ood-applications/files/bc_vizer/form.yml.erb
  playbooks/roles/ood-applications/files/bc_vizer/submit.yml.erb
  playbooks/roles/ood-applications/files/bc_vizer/template/before.sh.erb
  playbooks/roles/ood-applications/files/bc_vmd/readme.md
  playbooks/roles/ood-applications/files/bc_vmd/submit.yml.erb
  playbooks/roles/ood-applications/files/bc_vmd/template/script.sh.erb
Labels: kind/feature

#1802 Configurable list of remote viz queues
  .github/workflows/configs/almalinux.yml
  .github/workflows/configs/centos.yml
  .github/workflows/configs/integration.yml
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  playbooks/nodearray_lookup.yml
  playbooks/ood-overrides-common.yml
  playbooks/ood-overrides-openpbs.yml
  playbooks/ood-overrides-slurm.yml
  playbooks/ood.yml
  playbooks/roles/ood-applications/files/bc_ansys_workbench/form.yml.erb
  playbooks/roles/ood-applications/files/bc_paraview/form.yml.erb
  playbooks/roles/ood-applications/files/bc_vizer/form.yml.erb
  playbooks/roles/ood-applications/files/bc_vmd/form.yml.erb
  playbooks/roles/ood-applications/files/bc_vmd/template/xfce.sh
  playbooks/templates/viz_nodes.yml.j2
Labels: kind/feature, breaking-change

#1803 validate uniqueness of uids
  install.sh
Labels: kind/feature

#1805 enforce TLS 1.2 for the Active Directory VMs
  playbooks/ad.yml
  playbooks/ad2.yml
Labels: kind/feature

#1806 bump yq version to 4.40.5
  playbooks/ood.yml
  toolset/scripts/azhop-dependencies.yml
Labels: kind/feature

#1808 flag to disable NHC per queue
  config.schema.json
  config.tpl.yml
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/8-configure-nhc.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/99-healthcheck.sh
  playbooks/roles/cyclecloud_cluster/templates/azhop-OpenPBS.txt.j2
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
Labels: kind/feature

#1814 Use NVMe storage for enroot scratch when available
  playbooks/cccluster.yml
  playbooks/roles/cyclecloud_cluster/projects/enroot/cluster-init/scripts/2-install_enroot.sh.j2
  playbooks/scheduler.yml
Labels: kind/feature

#1815 backward compatibility for remote viz queues
  playbooks/templates/viz_nodes.yml.j2
Labels: kind/feature

#1816 update SIG API version
  bicep/sig.bicep
Labels: fix

#1788 Support for multi-region queues
  .github/workflows/configs/auth_ad.yml
  .github/workflows/configs/auth_local.yml
  bicep/azhop.bicep
  bicep/privatezone.bicep
  config.schema.json
  config.tpl.yml
  docs/deploy/index.md
  docs/images/pbs_autoscaler_hack.png
  playbooks/linux.yml
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/almalinux/init_joindomain.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/azhop-helpers.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/files/centos/init_joindomain.sh
  playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/3-joindomain.sh.j2
  playbooks/roles/cyclecloud_cluster/projects/openpbs/cluster-init/files/almalinux/installpbs.sh
  playbooks/roles/cyclecloud_cluster/projects/openpbs/cluster-init/scripts/2-installpbs.sh.j2
  playbooks/roles/cyclecloud_cluster/templates/azhop-OpenPBS.txt.j2
  playbooks/roles/cyclecloud_cluster/templates/azhop-slurm.txt.j2
  tf/anf.tf
  tf/main.tf
  tf/network/main.tf
  tf/private_dns.tf
  tf/variables_local.tf
Labels: kind/feature

#1819 Update slurm service to auto restart after 30s
  playbooks/roles/slurm/tasks/slurmserver.yml
Labels: fix

#1820 azhop admins are CycleCloud super users and Administrator
  playbooks/roles/cyclecloud/files/user_role_record.txt
  playbooks/templates/local_user_record.txt.j2
  playbooks/templates/user_record.txt.j2
Labels: kind/feature
